// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btwibdorrqdblbzlnlup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0d2liZG9ycnFkYmxiemxubHVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjQ1MjAsImV4cCI6MjA2MjcwMDUyMH0.q8p7qTXNy2yqkhclODlDTwUvDYmxRXD9RZS9LJDx0Ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);